// Curated emoji set with searchable keywords. Kept compact (~280 entries) so
// no extra runtime dep + no large JSON. Add more as you like.
export interface EmojiEntry { e: string; n: string; k?: string[] }

export const EMOJI: EmojiEntry[] = [
  // Smileys
  { e: '😀', n: 'grinning', k: ['smile', 'happy'] },
  { e: '😃', n: 'smiley', k: ['happy'] },
  { e: '😄', n: 'smile', k: ['happy', 'joy'] },
  { e: '😁', n: 'grin', k: ['happy'] },
  { e: '😆', n: 'laughing', k: ['lol', 'haha'] },
  { e: '😅', n: 'sweat_smile', k: ['phew', 'relieved'] },
  { e: '🤣', n: 'rofl', k: ['lol', 'laugh'] },
  { e: '😂', n: 'joy', k: ['lol', 'cry', 'laugh'] },
  { e: '🙂', n: 'slight_smile', k: ['smile'] },
  { e: '🙃', n: 'upside_down', k: ['flip'] },
  { e: '😉', n: 'wink', k: ['flirt'] },
  { e: '😊', n: 'blush', k: ['happy', 'smile'] },
  { e: '😇', n: 'innocent', k: ['halo', 'angel'] },
  { e: '🥰', n: 'smiling_hearts', k: ['love'] },
  { e: '😍', n: 'heart_eyes', k: ['love'] },
  { e: '🤩', n: 'star_struck', k: ['wow', 'awesome'] },
  { e: '😘', n: 'kiss', k: ['love'] },
  { e: '😗', n: 'kissing', k: [] },
  { e: '😚', n: 'kissing_closed_eyes', k: [] },
  { e: '😙', n: 'kissing_smiling_eyes', k: [] },
  { e: '🥲', n: 'smiling_tear', k: ['proud'] },
  { e: '😋', n: 'yum', k: ['tasty', 'tongue'] },
  { e: '😛', n: 'tongue', k: ['silly'] },
  { e: '😜', n: 'stuck_out_tongue_winking', k: ['silly'] },
  { e: '🤪', n: 'zany', k: ['crazy'] },
  { e: '😝', n: 'stuck_out_tongue_closed_eyes', k: [] },
  { e: '🤑', n: 'money_mouth', k: ['rich'] },
  { e: '🤗', n: 'hugs', k: ['hug'] },
  { e: '🤭', n: 'hand_over_mouth', k: ['oops'] },
  { e: '🤫', n: 'shush', k: ['quiet', 'silence'] },
  { e: '🤔', n: 'thinking', k: ['hmm', 'think'] },
  { e: '🤐', n: 'zipper_mouth', k: ['quiet'] },
  { e: '🤨', n: 'raised_eyebrow', k: ['skeptical'] },
  { e: '😐', n: 'neutral', k: ['meh'] },
  { e: '😑', n: 'expressionless', k: [] },
  { e: '😶', n: 'no_mouth', k: ['silent'] },
  { e: '😏', n: 'smirk', k: ['smug'] },
  { e: '😒', n: 'unamused', k: ['meh'] },
  { e: '🙄', n: 'roll_eyes', k: ['eyeroll'] },
  { e: '😬', n: 'grimacing', k: ['oops', 'awkward'] },
  { e: '🤥', n: 'lying', k: ['pinocchio'] },
  { e: '😌', n: 'relieved', k: ['phew'] },
  { e: '😔', n: 'pensive', k: ['sad'] },
  { e: '😪', n: 'sleepy', k: ['tired'] },
  { e: '🤤', n: 'drool', k: ['hungry'] },
  { e: '😴', n: 'sleeping', k: ['zzz', 'tired'] },
  { e: '😷', n: 'mask', k: ['sick'] },
  { e: '🤒', n: 'thermometer', k: ['sick', 'fever'] },
  { e: '🤕', n: 'head_bandage', k: ['hurt'] },
  { e: '🤢', n: 'nauseated', k: ['sick'] },
  { e: '🤮', n: 'vomit', k: ['sick'] },
  { e: '🤧', n: 'sneeze', k: ['sick'] },
  { e: '🥵', n: 'hot', k: ['heat', 'sweat'] },
  { e: '🥶', n: 'cold', k: ['freeze'] },
  { e: '😵', n: 'dizzy', k: ['ko'] },
  { e: '🤯', n: 'mind_blown', k: ['exploding', 'wow'] },
  { e: '🤠', n: 'cowboy', k: ['hat'] },
  { e: '🥳', n: 'partying', k: ['party', 'celebrate'] },
  { e: '🥸', n: 'disguise', k: [] },
  { e: '😎', n: 'sunglasses', k: ['cool'] },
  { e: '🤓', n: 'nerd', k: ['geek'] },
  { e: '🧐', n: 'monocle', k: ['inspect'] },
  { e: '😕', n: 'confused', k: [] },
  { e: '😟', n: 'worried', k: [] },
  { e: '🙁', n: 'slight_frown', k: ['sad'] },
  { e: '☹️', n: 'frown', k: ['sad'] },
  { e: '😮', n: 'open_mouth', k: ['surprised', 'wow'] },
  { e: '😯', n: 'hushed', k: ['surprised'] },
  { e: '😲', n: 'astonished', k: ['shocked'] },
  { e: '😳', n: 'flushed', k: ['embarrassed'] },
  { e: '🥺', n: 'pleading', k: ['puppy'] },
  { e: '😦', n: 'frowning_open', k: [] },
  { e: '😧', n: 'anguished', k: [] },
  { e: '😨', n: 'fearful', k: ['scared'] },
  { e: '😰', n: 'anxious_sweat', k: [] },
  { e: '😥', n: 'sad_but_relieved', k: [] },
  { e: '😢', n: 'cry', k: ['sad', 'tear'] },
  { e: '😭', n: 'sob', k: ['cry', 'sad'] },
  { e: '😱', n: 'scream', k: ['shock', 'fear'] },
  { e: '😖', n: 'confounded', k: [] },
  { e: '😣', n: 'persevere', k: [] },
  { e: '😞', n: 'disappointed', k: ['sad'] },
  { e: '😓', n: 'sweat', k: [] },
  { e: '😩', n: 'weary', k: ['tired'] },
  { e: '😫', n: 'tired', k: [] },
  { e: '🥱', n: 'yawn', k: ['sleepy'] },
  { e: '😤', n: 'triumph', k: ['huff'] },
  { e: '😡', n: 'rage', k: ['angry'] },
  { e: '😠', n: 'angry', k: ['mad'] },
  { e: '🤬', n: 'cursing', k: ['swear', 'angry'] },
  { e: '😈', n: 'imp', k: ['devil'] },
  { e: '👿', n: 'angry_devil', k: [] },
  { e: '💀', n: 'skull', k: ['dead', 'lol'] },
  { e: '☠️', n: 'skull_crossbones', k: [] },
  { e: '💩', n: 'poop', k: ['shit'] },
  { e: '🤡', n: 'clown', k: [] },
  { e: '👻', n: 'ghost', k: ['boo'] },
  { e: '👽', n: 'alien', k: ['ufo'] },
  { e: '👾', n: 'space_invader', k: ['game'] },
  { e: '🤖', n: 'robot', k: ['ai', 'bot'] },
  // Hands & body
  { e: '👍', n: 'thumbs_up', k: ['like', 'yes', '+1'] },
  { e: '👎', n: 'thumbs_down', k: ['dislike', 'no', '-1'] },
  { e: '👌', n: 'ok_hand', k: [] },
  { e: '🤌', n: 'pinched_fingers', k: ['italian'] },
  { e: '🤏', n: 'pinch', k: ['small'] },
  { e: '✌️', n: 'peace', k: ['victory'] },
  { e: '🤞', n: 'crossed_fingers', k: ['luck'] },
  { e: '🤟', n: 'love_you', k: ['ily'] },
  { e: '🤘', n: 'rock_on', k: ['horns'] },
  { e: '🤙', n: 'call_me', k: ['shaka'] },
  { e: '👈', n: 'point_left', k: [] },
  { e: '👉', n: 'point_right', k: [] },
  { e: '👆', n: 'point_up', k: [] },
  { e: '👇', n: 'point_down', k: [] },
  { e: '☝️', n: 'index_pointing_up', k: [] },
  { e: '✋', n: 'raised_hand', k: ['hi', 'stop'] },
  { e: '🤚', n: 'raised_back_of_hand', k: [] },
  { e: '🖐️', n: 'splayed_hand', k: [] },
  { e: '🖖', n: 'vulcan', k: ['spock', 'startrek'] },
  { e: '👋', n: 'wave', k: ['hi', 'hello', 'bye'] },
  { e: '🤝', n: 'handshake', k: ['deal'] },
  { e: '👏', n: 'clap', k: ['applause'] },
  { e: '🙌', n: 'raised_hands', k: ['praise'] },
  { e: '👐', n: 'open_hands', k: [] },
  { e: '🤲', n: 'palms_up', k: ['pray'] },
  { e: '🙏', n: 'pray', k: ['thanks', 'thank you', 'please'] },
  { e: '✍️', n: 'writing_hand', k: ['write'] },
  { e: '💪', n: 'muscle', k: ['strong', 'flex'] },
  { e: '🦾', n: 'mechanical_arm', k: [] },
  { e: '🦿', n: 'mechanical_leg', k: [] },
  { e: '👀', n: 'eyes', k: ['look', 'see'] },
  { e: '👁️', n: 'eye', k: [] },
  { e: '👅', n: 'tongue', k: [] },
  { e: '👄', n: 'lips', k: ['mouth'] },
  { e: '🧠', n: 'brain', k: ['smart'] },
  // Hearts & symbols
  { e: '❤️', n: 'heart', k: ['love', 'red'] },
  { e: '🧡', n: 'orange_heart', k: [] },
  { e: '💛', n: 'yellow_heart', k: [] },
  { e: '💚', n: 'green_heart', k: [] },
  { e: '💙', n: 'blue_heart', k: [] },
  { e: '💜', n: 'purple_heart', k: [] },
  { e: '🖤', n: 'black_heart', k: [] },
  { e: '🤍', n: 'white_heart', k: [] },
  { e: '🤎', n: 'brown_heart', k: [] },
  { e: '💔', n: 'broken_heart', k: ['sad'] },
  { e: '❣️', n: 'heart_exclamation', k: [] },
  { e: '💕', n: 'two_hearts', k: ['love'] },
  { e: '💖', n: 'sparkling_heart', k: ['love'] },
  { e: '💗', n: 'growing_heart', k: [] },
  { e: '💘', n: 'cupid', k: ['love'] },
  { e: '💝', n: 'gift_heart', k: [] },
  { e: '💞', n: 'revolving_hearts', k: [] },
  { e: '💟', n: 'heart_decoration', k: [] },
  { e: '💯', n: 'hundred', k: ['100', 'perfect'] },
  { e: '✨', n: 'sparkles', k: ['shiny', 'star', 'magic'] },
  { e: '⭐', n: 'star', k: [] },
  { e: '🌟', n: 'glowing_star', k: [] },
  { e: '💫', n: 'dizzy_sparkle', k: [] },
  { e: '⚡', n: 'zap', k: ['lightning', 'fast'] },
  { e: '🔥', n: 'fire', k: ['lit', 'hot', 'flame'] },
  { e: '💥', n: 'boom', k: ['explosion'] },
  { e: '☀️', n: 'sun', k: [] },
  { e: '🌙', n: 'moon', k: ['night'] },
  { e: '🌈', n: 'rainbow', k: ['pride'] },
  { e: '☁️', n: 'cloud', k: [] },
  { e: '❄️', n: 'snowflake', k: ['snow', 'cold'] },
  { e: '🌊', n: 'wave', k: ['ocean', 'water'] },
  // Objects / productivity
  { e: '✅', n: 'check', k: ['done', 'yes', 'tick'] },
  { e: '☑️', n: 'check_box', k: [] },
  { e: '✔️', n: 'check_mark', k: [] },
  { e: '❌', n: 'x', k: ['no', 'cross', 'cancel'] },
  { e: '❎', n: 'cross_box', k: [] },
  { e: '⚠️', n: 'warning', k: ['alert'] },
  { e: '🚨', n: 'rotating_light', k: ['alert', 'siren'] },
  { e: '🔔', n: 'bell', k: ['notify'] },
  { e: '🔕', n: 'no_bell', k: ['mute'] },
  { e: '📌', n: 'pushpin', k: ['pin'] },
  { e: '📍', n: 'round_pin', k: ['location'] },
  { e: '🔗', n: 'link', k: ['url'] },
  { e: '📎', n: 'paperclip', k: ['attach'] },
  { e: '🖇️', n: 'paperclips', k: [] },
  { e: '📁', n: 'folder', k: ['file'] },
  { e: '📂', n: 'open_folder', k: [] },
  { e: '🗂️', n: 'card_index_dividers', k: [] },
  { e: '📅', n: 'calendar', k: ['date'] },
  { e: '📆', n: 'tear_off_calendar', k: [] },
  { e: '🗓️', n: 'spiral_calendar', k: [] },
  { e: '📇', n: 'card_index', k: [] },
  { e: '📈', n: 'chart_up', k: ['trend'] },
  { e: '📉', n: 'chart_down', k: [] },
  { e: '📊', n: 'bar_chart', k: ['stats'] },
  { e: '📋', n: 'clipboard', k: [] },
  { e: '📝', n: 'memo', k: ['note', 'write'] },
  { e: '📓', n: 'notebook', k: [] },
  { e: '📔', n: 'notebook_decorative', k: [] },
  { e: '📕', n: 'closed_book', k: [] },
  { e: '📗', n: 'green_book', k: [] },
  { e: '📘', n: 'blue_book', k: [] },
  { e: '📙', n: 'orange_book', k: [] },
  { e: '📚', n: 'books', k: ['read'] },
  { e: '📖', n: 'open_book', k: ['read'] },
  { e: '🔖', n: 'bookmark', k: [] },
  { e: '🏷️', n: 'label', k: ['tag'] },
  { e: '💡', n: 'bulb', k: ['idea', 'tip'] },
  { e: '🔦', n: 'flashlight', k: [] },
  { e: '🕯️', n: 'candle', k: [] },
  { e: '🔍', n: 'magnify', k: ['search', 'find'] },
  { e: '🔎', n: 'magnify_right', k: [] },
  { e: '🔒', n: 'lock', k: ['secure', 'private'] },
  { e: '🔓', n: 'unlock', k: [] },
  { e: '🔑', n: 'key', k: [] },
  { e: '🗝️', n: 'old_key', k: [] },
  { e: '🛠️', n: 'tools', k: ['build', 'fix'] },
  { e: '🔧', n: 'wrench', k: ['fix'] },
  { e: '🔨', n: 'hammer', k: ['build'] },
  { e: '⚙️', n: 'gear', k: ['settings'] },
  { e: '🧰', n: 'toolbox', k: [] },
  { e: '🧲', n: 'magnet', k: [] },
  { e: '⚗️', n: 'alembic', k: ['lab'] },
  { e: '🧪', n: 'test_tube', k: ['science'] },
  { e: '🧫', n: 'petri_dish', k: [] },
  { e: '🧬', n: 'dna', k: ['genetics'] },
  { e: '🔬', n: 'microscope', k: ['science'] },
  { e: '🔭', n: 'telescope', k: ['space'] },
  { e: '💻', n: 'laptop', k: ['computer', 'pc'] },
  { e: '🖥️', n: 'desktop', k: ['computer'] },
  { e: '⌨️', n: 'keyboard', k: [] },
  { e: '🖱️', n: 'mouse', k: [] },
  { e: '🖨️', n: 'printer', k: [] },
  { e: '📱', n: 'phone', k: ['mobile'] },
  { e: '📞', n: 'telephone', k: ['call'] },
  { e: '☎️', n: 'old_phone', k: [] },
  { e: '📧', n: 'email', k: ['mail'] },
  { e: '✉️', n: 'envelope', k: ['mail'] },
  { e: '📨', n: 'incoming_envelope', k: [] },
  { e: '📤', n: 'outbox', k: ['send'] },
  { e: '📥', n: 'inbox', k: [] },
  { e: '📦', n: 'package', k: ['box'] },
  { e: '📬', n: 'mailbox_with_mail', k: [] },
  { e: '🗳️', n: 'ballot_box', k: ['vote'] },
  { e: '🗑️', n: 'trash', k: ['delete'] },
  { e: '🪣', n: 'bucket', k: [] },
  { e: '⏰', n: 'alarm', k: ['clock', 'time'] },
  { e: '⏱️', n: 'stopwatch', k: ['timer'] },
  { e: '⏲️', n: 'timer', k: [] },
  { e: '🕐', n: 'one_oclock', k: ['time'] },
  { e: '⌛', n: 'hourglass_done', k: ['wait'] },
  { e: '⏳', n: 'hourglass', k: ['wait'] },
  { e: '🚀', n: 'rocket', k: ['launch', 'ship'] },
  { e: '🎯', n: 'bullseye', k: ['target', 'goal'] },
  { e: '🏆', n: 'trophy', k: ['win'] },
  { e: '🥇', n: 'gold_medal', k: ['first', '1st'] },
  { e: '🥈', n: 'silver_medal', k: ['second'] },
  { e: '🥉', n: 'bronze_medal', k: ['third'] },
  { e: '🎖️', n: 'medal', k: [] },
  { e: '🏅', n: 'sports_medal', k: [] },
  { e: '🎉', n: 'tada', k: ['party', 'celebrate'] },
  { e: '🎊', n: 'confetti', k: [] },
  { e: '🎁', n: 'gift', k: ['present'] },
  { e: '🎈', n: 'balloon', k: ['party'] },
  { e: '🎂', n: 'birthday', k: ['cake'] },
  { e: '🍰', n: 'cake', k: [] },
  { e: '☕', n: 'coffee', k: ['cafe'] },
  { e: '🍵', n: 'tea', k: ['chai'] },
  { e: '🍺', n: 'beer', k: [] },
  { e: '🍻', n: 'beers', k: ['cheers'] },
  { e: '🍷', n: 'wine', k: [] },
  { e: '🍕', n: 'pizza', k: ['food'] },
  { e: '🍔', n: 'burger', k: ['food'] },
  { e: '🍟', n: 'fries', k: [] },
  { e: '🌮', n: 'taco', k: [] },
  { e: '🍣', n: 'sushi', k: [] },
  { e: '🍜', n: 'ramen', k: ['noodles'] },
  { e: '🍎', n: 'apple', k: ['fruit'] },
  { e: '🍌', n: 'banana', k: ['fruit'] },
  { e: '🥑', n: 'avocado', k: [] },
  { e: '🌶️', n: 'chili', k: ['spicy', 'hot'] },
  { e: '🐶', n: 'dog', k: ['puppy'] },
  { e: '🐱', n: 'cat', k: ['kitty'] },
  { e: '🦊', n: 'fox', k: [] },
  { e: '🐼', n: 'panda', k: [] },
  { e: '🦄', n: 'unicorn', k: ['magic'] },
  { e: '🐉', n: 'dragon', k: [] },
  { e: '🦋', n: 'butterfly', k: [] },
  // Misc productivity icons
  { e: '🚧', n: 'construction', k: ['wip'] },
  { e: '🏗️', n: 'construction_crane', k: ['build'] },
  { e: '🛡️', n: 'shield', k: ['protect', 'security'] },
  { e: '🪪', n: 'id', k: [] },
  { e: '🌍', n: 'earth', k: ['world', 'globe'] },
  { e: '🌐', n: 'globe', k: ['internet', 'web'] },
  { e: '🇮🇳', n: 'flag_in', k: ['india'] },
  { e: '🇺🇸', n: 'flag_us', k: ['usa', 'america'] },
];

export function searchEmoji(query: string, limit = 12): EmojiEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return EMOJI.slice(0, limit);
  const out: { item: EmojiEntry; score: number }[] = [];
  for (const it of EMOJI) {
    const name = it.n.toLowerCase();
    let score = 0;
    if (name === q) score = 100;
    else if (name.startsWith(q)) score = 60;
    else if (name.includes(q)) score = 40;
    else if (it.k?.some(k => k.toLowerCase().startsWith(q))) score = 30;
    else if (it.k?.some(k => k.toLowerCase().includes(q))) score = 15;
    if (score > 0) out.push({ item: it, score });
  }
  out.sort((a, b) => b.score - a.score);
  return out.slice(0, limit).map(o => o.item);
}
