// Curated topic vocabulary for auto-tagging via semantic similarity.
export const TOPIC_VOCAB: string[] = [
  'productivity', 'philosophy', 'engineering', 'meeting', 'idea', 'todo',
  'reading', 'health', 'fitness', 'finance', 'investing', 'travel', 'cooking',
  'recipe', 'journal', 'reflection', 'gratitude', 'mindfulness', 'meditation',
  'goals', 'planning', 'project', 'research', 'learning', 'study', 'notes',
  'writing', 'design', 'art', 'music', 'movies', 'books', 'review',
  'programming', 'javascript', 'typescript', 'python', 'rust', 'web',
  'frontend', 'backend', 'database', 'algorithm', 'machine learning', 'ai',
  'data science', 'statistics', 'math', 'physics', 'chemistry', 'biology',
  'science', 'history', 'politics', 'economics', 'business', 'startup',
  'marketing', 'sales', 'product', 'strategy', 'leadership', 'management',
  'team', 'hiring', 'interview', 'career', 'resume', 'networking',
  'family', 'friends', 'relationship', 'personal', 'work', 'school',
  'home', 'shopping', 'errands', 'hobby', 'gaming', 'sports', 'outdoors',
  'nature', 'weather', 'gardening', 'photography', 'language', 'spanish',
  'french', 'german', 'japanese', 'chinese', 'culture', 'religion',
  'spirituality', 'ethics', 'psychology', 'sociology', 'anthropology',
  'medicine', 'mental health', 'sleep', 'nutrition', 'diet', 'workout',
  'running', 'cycling', 'yoga', 'climbing', 'swimming', 'hiking',
  'recipe ideas', 'meal prep', 'budget', 'taxes', 'savings', 'crypto',
  'stocks', 'real estate', 'productivity tips', 'time management',
  'habits', 'routine', 'morning', 'evening', 'weekly review', 'quarterly',
  'annual', 'vision', 'mission', 'values', 'principles', 'quotes',
  'inspiration', 'motivation', 'lessons learned', 'mistakes', 'wins',
  'losses', 'feedback', 'retrospective', 'standup', 'one on one',
  'documentation', 'spec', 'architecture', 'system design', 'api', 'security',
  'devops', 'infrastructure', 'cloud', 'aws', 'docker', 'kubernetes',
  'testing', 'debugging', 'refactoring', 'code review', 'git', 'open source',
  'side project', 'launch', 'mvp', 'roadmap', 'backlog', 'sprint',
  'kanban', 'agile', 'scrum', 'okr', 'kpi', 'metric', 'analytics',
  'experiment', 'hypothesis', 'survey', 'user research', 'ux', 'ui',
  'accessibility', 'performance', 'optimization', 'scaling',
  'shopping list', 'gift ideas', 'birthday', 'anniversary', 'holiday',
  'vacation', 'trip planning', 'packing', 'flights', 'hotels',
  'restaurant', 'cafe', 'date night', 'event', 'party', 'wedding',
  'baby', 'parenting', 'kids', 'pets', 'dog', 'cat',
  'medication', 'doctor', 'appointment', 'symptoms', 'therapy',
  'budget plan', 'expense tracking', 'invoice', 'contract', 'legal',
  'agreement', 'policy', 'compliance', 'risk', 'audit',
  'brainstorm', 'mind map', 'outline', 'draft', 'edit', 'publish',
  'blog', 'newsletter', 'podcast', 'video', 'tutorial', 'course',
  'lecture', 'class notes', 'flashcards', 'vocabulary', 'grammar',
  'thesis', 'paper', 'citation', 'bibliography', 'literature review',
  'conference', 'workshop', 'webinar', 'training', 'certification',
];
